# weather-infra/environments/favourite-api/values.yaml
useRollout: true
replicaCount: 2

image:
  repository: 943347376383.dkr.ecr.us-east-2.amazonaws.com/favourite-api
  tag: "v2.0.0"

service:
  port: 4000

ingress:
  enabled: true
  className: nginx
  activeHost:  favourite-api.prod.example.com
  previewHost: favourite-api-preview.prod.example.com

# ── NEW ───────────────────────────────────────────────
rollout:
  autoPromotionEnabled: false      # flip to true if you want auto-promote
# ──────────────────────────────────────────────────────
nameOverride: favourite-api-uat