#weather-infra/environments/favourite-api/values.yaml
# ---------- favourite-api · PROD values ----------
useRollout: true
replicaCount: 3

image:
  repository: 943347376383.dkr.ecr.us-east-2.amazonaws.com/favourite-api
  tag: "v3.1.8"

service:
  port: 4000

ingress:
  enabled: false
  className: nginx
  activeHost: favourite-api.prod.example.com
  previewHost: favourite-api-preview.prod.example.com

rollout:
  autoPromotionEnabled: false      # manual gate
  scaleDownDelaySeconds: 30        # old pods culled 30 s after promotion
