#weather-infra/helm/charts/umbrella/values.yaml
replicaCount: 2

# UAT keeps the default “false” — PROD sets this to true
useRollout: false

image:
  repository: ""
  tag: ""

service:
  type: ClusterIP
  port: 4000

ingress:
  enabled: true
  className: nginx
  hosts: []        # override per environment
