#weather-infra/environments/uat/weather-frontend/values.yaml
image:
  repository: 943347376383.dkr.ecr.us-east-2.amazonaws.com/weather-frontend
  tag: ""
service:
  port: 80               # frontend listens on 80

ingress:
  enabled: false
