#weather-infra/environments/weather-frontend/values.yaml
# ---------- weather-frontend · PROD values ----------
useRollout: true
replicaCount: 3

image:
  repository: 943347376383.dkr.ecr.us-east-2.amazonaws.com/weather-frontend
  tag: "v3.1.8"

service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

ingress:
  enabled: false
  className: nginx
  activeHost: weather.prod.example.com
  previewHost: weather-preview.prod.example.com

rollout:
  autoPromotionEnabled: false
  scaleDownDelaySeconds: 30
