useRollout: true
replicaCount: 3

image:
  repository: 943347376383.dkr.ecr.us-east-2.amazonaws.com/weather-api
  tag: "v1.4.0"

service:
  port: 4000

ingress:
  enabled: true
  hosts:
    - host: weather-api.prod.example.com
      paths:
        - path: /
          pathType: Prefix

extraEnv:
  - name: OPENWEATHER_API_KEY
    value: "${OPENWEATHER_API_KEY}"

