apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-prod
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc   # this Argo CD’s own cluster
    namespace: argocd
  source:
    repoURL: https://github.com/Sufiyan11919/weather-infra.git
    targetRevision: main
    path: argocd/prod/apps                  # folder with the three prod apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
