# weather-infra/prod/argocd/rbac/argocd-controller.yaml
#
# Gives the Argo CD *application-controller* in the argocd-prod namespace
# the same cluster-wide permissions it has in UAT.
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-prod-application-controller
  labels:
    app.kubernetes.io/part-of: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-application-controller          # ← already created by the install
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd-prod                       # ← **must match** your prod install
