apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: weather-frontend
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: weather-frontend-svc     # BLUE
      previewService: weather-frontend-preview # GREEN
      autoPromotionEnabled: false             # manual click
  selector:
    matchLabels: { app: weather-frontend }
  template:
    metadata: { labels: { app: weather-frontend } }
    spec:
      containers:
      - name: web
        image: 943347376383.dkr.ecr.us-east-2.amazonaws.com/weather-frontend:latest
        ports: [{ containerPort: 80 }]
