#weather-infra/prod/helm/umbrella/templates/rollout.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "weather.fullname" . }}
  labels:
    app: {{ include "weather.fullname" . }}
spec:
  replicas: {{ .Values.replicas | default 2 }}
  strategy:
    blueGreen:
      activeService: {{ include "weather.fullname" . }}
      previewService: {{ include "weather.fullname" . }}-preview
      autoPromotionEnabled: {{ .Values.rollout.autoPromotionEnabled | default false }}
  selector:
    matchLabels:
      app: {{ include "weather.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "weather.fullname" . }}
    spec:
      containers:
        - name: main
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ENVIRONMENT
              value: "prod"
          resources: {{- toYaml .Values.resources | nindent 12 }}