#weather-infra/prod/helm/umbrella/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "weather.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "weather.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http