name: Promote to PROD (Argo Rollout)

on:
  pull_request:
    types: [labeled]

jobs:
  prod:
    if: contains(github.event.pull_request.labels.*.name, 'promote-prod')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Inject image tag & commit
      env:
        SVC: ${{ github.event.pull_request.title }}   # e.g. weather-frontend
        SHA: ${{ github.event.pull_request.head.sha }}
      run: ./scripts/prod_apply.sh "$SVC" "$SHA"
